language: node_js
node_js:
- iojs
env: FDB_VERSION=3.0.6
before_install:
# Install FoundationDB
- wget https://foundationdb.com/downloads/I_accept_the_FoundationDB_Community_License_Agreement/key-value-store/${FDB_VERSION}/foundationdb-clients_${FDB_VERSION}-1_amd64.deb
- wget https://foundationdb.com/downloads/I_accept_the_FoundationDB_Community_License_Agreement/key-value-store/${FDB_VERSION}/foundationdb-server_${FDB_VERSION}-1_amd64.deb
- sudo dpkg -i foundationdb-server_${FDB_VERSION}-1_amd64.deb foundationdb-clients_${FDB_VERSION}-1_amd64.deb
- rm foundationdb-server_${FDB_VERSION}-1_amd64.deb foundationdb-clients_${FDB_VERSION}-1_amd64.deb
# Run ESLint
- npm install -g eslint
- curl 'https://raw.githubusercontent.com/ripple/javascript-style-guide/es6/eslintrc' > ./.eslintrc
- eslint .
script: MOCHA_REPORTER=tap npm test --coverage
after_success:
- npm run coveralls
notifications:
  slack:
    secure: bltLEOkw+Kv8g1EUYKbu848r+Fx8Rhhc54wagwgaHPYYRi/ipV5xyQMP4NRJvoMKFNAws16ytUcRXqaNz4tolOx1XWckcjb3KYwFAku9rumSfxjiJGN97UsJadjL8OXnSJrwtPv7yyWnqrhj8UB16MLNx4HTRLjblUWFJDqdbaI=
